language: python
python: 3.6
env:
- PKG_NAME=struct_lmm
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: rachelmoore
  password:
    secure: enH6LQgx5rYvmmhTSVP1wsV56LvMOfJ8GMKuhMh6lwM/hWwoQigp9wZbBbXQgQSGC+vV+J3vQnVDZT36CPlPVnT/mPpu/sBxZ8yLzt+RRNmjEi2r9Pghh/tawcxKp0WSrKJ5sIEBSMEy1sfLAXpDDM12xyA5NBsaxnyzGeYzDnbmS+C7Hp70w9AW70P1DHZzmnRlyueiQOx4o28BXowiRwRjLtqwruKYtz0ohusC12xXRpl3ynrOCDffMkIyfyIKjJ+g7pzSEYGx8jVeVINpRCQeJMvQZlEPstf9u4zKDKhGNc0nj94ZAPTvulk1S3g4b7WLduCed0W0F0GmGUBqR1RUhADreAnGrUeIeMcLxx4iyDLqZU1RPrunmKf9P3n6q00Ei7ngCDr2irUoj6uKAlFLP9qpjgP/7oT7iDh0THNdCjk/5kbu8JniGkedXpsRmYGrBcPeDpDdIQIu2DuvH42eaQ98TSdYsQF8zBNJgjHg1O+k+uui9Mg9HUwfjBMGsgydUIy1oRMgM6IbctVULXX5vu+CYXGhEkTcw7CxfKyLLW/7n7W4dWfMnjIiAF0e3+AfmelMOOAa2tDCLE/Kj5gnnAmbmy5LFmhE38qNpt6B1tjSbVePfl7oDJdmDocI65Mhpmc0zTiXv8NN06ZWBugpDze26NIc8wHc83ZtTzo=
  on:
    tags: true
    repo: limix/struct-lmm
    branch: master
    python: 3.6
